\pset null _null_

SET client_min_messages = warning;
SET ROLE postgres;

create table tab_generated12 (
       a integer generated by default as identity,
       b integer generated always as identity,
       c integer generated always as (a+b) stored,
       d integer default 42,
       e serial,
       f integer
);

-- select * from ddlx_describe('tab_generated12'::regclass) d;

\pset format unaligned
select ddlx_script('tab_generated12');
